security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        main:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            guard:
                authenticators:
                    - AppBundle\Authenticator\UserAuthenticator
            form_login:
                login_path: tdl_login
                check_path: tdl_login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:       tdl_logout
                target:     tdl_login
            logout_on_user_change: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }